spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/investment_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # Set to none so script generation handles schema definition
    show-sql: true
    properties:
      jakarta:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: src/main/resources/db/migration/V1__init_schema.sql
      hibernate:
        format_sql: true

  flyway:
    enabled: true